# Generated by Django 3.2.3 on 2021-05-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
    ]
